### ISSUE TITLE
Error log re teleport pipe (not crashing game)

### ISSUE THREAD

**Issue by xanthian** [PTOM76/PipePlus#9]
[Render thread/ERROR]: Parsing error loading recipe pipeplus:crafting/pipe_items_teleport
com.google.gson.JsonSyntaxException: Unknown item tag 'c:diamond_gears'
	at net.minecraft.class_1856.method_17873(class_1856.java:164) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_5415.method_33166(class_5415.java:49) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:164) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1869.method_8157(class_1869.java:233) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:265) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:260) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-1.17.1.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_310.method_29604(class_310.java:2152) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_310.method_29610(class_310.java:1999) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_310.method_29606(class_310.java:1939) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:437) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:343) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:274) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_350.method_25402(class_350.java:359) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:490) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:94) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) ~[intermediary-1.17.1.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) [lwjgl-glfw-3.2.2.jar:build 10]
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133) [FpsReducer-fabric-1.24-mc1.17.1.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.handler$bhk000$handleWaitEventsTimeout(RenderSystem.java:1422) [intermediary-1.17.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java) [intermediary-1.17.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1140) [intermediary-1.17.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568) [fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.5.jar:?]

**Comment by PTOM76** [comment]
There are auxiliary recipes. So you can safely ignore this.
